### PR TITLE
Fix: add image dimensions into header image customization

### LINKED ISSUE #790: Images in headers still don't have image dimensions
Previously I had an issue about [this very thing](https://github.com/presscustomizr/hueman/issues/300). Unfortunately this issue still exists today.

This is still something that is needed and beneficiary when optimizing a website. Even GTMetrix will flag this as an issue.

What can we do to resolve this?

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
using the standard wp function get_header_image_tag
fixes #790 #300

### CODE REVIEW

**Comment by ghost** [comment]
Thanks
@eri-trabiccolo can you confirm that the contextualizer still works fine with this implementation ?
( just to be sure... )

**Comment by ghost** [comment]
I'll check on my side. no worries

**Comment by eri-trabiccolo** [comment]
I've tested it yes, worked fine, consider that the former and the new version basically use the same "family" of wp functions...
(remember to build the css when testing.)

**Comment by ghost** [comment]
Thanks !

**Pull request merged**
