### PR TITLE
Revert "Remove tracking code field"

### PR DESCRIPTION
**Pull request by andreaskas**
This reverts commit 13c5e3f8280fae2c547112ef8d9655e3392d94ca.

As said at issue #106 please accept this revert to avoid extra complexity in case a user wants to add a tracking code. By removing it, the user must edit footer file or the file that he wants to make the tracking code appear or install a plug-in to do it. From the moment that this option was a feature for a long time, please add it back for the reasons mentioned above.

### CODE REVIEW

**Comment by andreaskas** [comment]
@AlxMedia what do you thing?

**Comment by carminexx** [comment]
+1

**Comment by andreaskas** [comment]
I also added some missing CSS attributes for some new input types introduced at HTML5 for both themeform and wpcf7 classes. For now only the three basics url,tel,number are supported.I will add in the near future the code for the other types.

**Comment by jaylinski** [comment]
@andreaskas you should create a separate pull request for the css changes. the tracking-code-revert probably won't be merged.

**Comment by andreaskas** [comment]
New branch created and i reverted the commit about CSS at this branch pull #114

**Pull request closed without merging**
